### ISSUE TITLE
`Valid` and `MappingRulesVerified` condition names are not intuitive.

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#130]
Seeing following conditions suggested to me that `Valid` condition pertains to source VM validation and `MappingRulesVerified` to resource mapping validation, while in reality it is the other way around  and as designed.

```
  status:
    conditions:
    - lastHeartbeatTime: "2020-04-21T16:34:29Z"
      lastTransitionTime: "2020-04-21T16:34:29Z"
      message: Validation completed successfully
      reason: ValidationCompleted
      status: "True"
      type: Valid
    - lastHeartbeatTime: "2020-04-21T16:36:29Z"
      lastTransitionTime: "2020-04-21T16:36:29Z"
      message: VM has no disks
      reason: MappingRulesVerificationFailed
      status: "False"
      type: MappingRulesVerified
```

If the confusion is more comon, we should think about renaming the two conditions.
