### ISSUE TITLE
created VM is missing important labels and an annotation

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#149]
These are the labels and one annotation which are required by the UI:

VM created from example template in UI:

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
    name.os.template.kubevirt.io/fedora31: Fedora 31
  name: asd
  namespace: default
  labels:
    app: asd
    flavor.template.kubevirt.io/tiny: 'true'
    os.template.kubevirt.io/fedora31: 'true'
    vm.kubevirt.io/template: vm-template-example
    vm.kubevirt.io/template.namespace: default
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.9.1
    workload.template.kubevirt.io/server: 'true'
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        flavor.template.kubevirt.io/tiny: 'true'
        kubevirt.io/domain: asd
        kubevirt.io/size: tiny
        os.template.kubevirt.io/fedora31: 'true'
        vm.kubevirt.io/name: asd
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:dd:94:00:00:02'
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 1Gi
      hostname: asd
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: 'kubevirt/fedora-cloud-container-disk-demo:latest'
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk

```

**Comment by atiratree** [comment]
please note that VMI has also its own set of labels

**Comment by atiratree** [comment]
compared to the one created by VMImport:

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    comment: ''
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
    sso: guest_agent
  name: win2012demo
  namespace: default
  labels:
    app: win2012demo
    origin: rhev
    tags: ''
    vm.kubevirt.io/template: win2k12r2-desktop-medium-v0.7.0
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.9.1
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: win2012demo
        kubevirt.io/size: medium
    spec:
      domain:
        clock:
.
.
.
```

**Comment by atiratree** [comment]
VM created from template is still missing these

```yaml
metadata:
  annotations:
    name.os.template.kubevirt.io/fedora31: Fedora 31
  labels:
    vm.kubevirt.io/template.namespace: default
```

VM created without template is missing all labels. Not all are applicable though, we are setting these in the UI:

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/fedora31: Fedora 31
  name: fedora
  namespace: default
  labels:
    app: fedora
    flavor.template.kubevirt.io/Custom: 'true'
    os.template.kubevirt.io/fedora31: 'true'
spec:
  running: false
  template:
    metadata:
      labels:
        flavor.template.kubevirt.io/Custom: 'true'
        kubevirt.io/domain: fedora
        os.template.kubevirt.io/fedora31: 'true'
        vm.kubevirt.io/name: fedora
    spec:
```
