### ISSUE TITLE
VMIMports condition may override existing condition

### ISSUE THREAD

**Issue by masayag** [kubevirt/vm-import-operator#322]
When running a VM Import that fails due to a missing secret (or other failure to initialize the provider),  it may be that both conditions are recorded as expected, e.g. for the expected scenario the status should contain both condition types 'Valid' and 'Succeedeed' :
```
  conditions:
  - lastHeartbeatTime: "2020-07-02T16:20:16Z"
    lastTransitionTime: "2020-07-02T16:20:16Z"
    message: 'Failed to connect to source provider: Post /ovirt-engine/sso/oauth/token:
      unsupported protocol scheme ""'
    reason: UnreachableProvider
    status: "False"
    type: Valid
  - lastHeartbeatTime: "2020-07-02T16:20:16Z"
    lastTransitionTime: "2020-07-02T16:20:16Z"
    message: 'Failed to initialize the source provider (Failed to connect to source
      provider): Post /ovirt-engine/sso/oauth/token: unsupported protocol scheme ""'
    reason: ValidationFailed
    status: "False"
    type: Succeeded
```

However in some cases only the latter condition is kept and overrides the previous condition.
When watching the status of the CR it looks that 'Valid' is recorded:
```
status:
  conditions:
  - lastHeartbeatTime: "2020-07-02T15:12:41Z"
    lastTransitionTime: "2020-07-02T15:12:41Z"
    message: Secret not found
    reason: SecretNotFound
    status: "False"
    type: Valid
```
And then it is overridden with:
```
status:
  conditions:
  - lastHeartbeatTime: "2020-07-02T15:12:41Z"
    lastTransitionTime: "2020-07-02T15:12:41Z"
    message: 'Failed to initialize the source provider (Secret not found): Secret
      "no-such-secret" not found'
    reason: ValidationFailed
    status: "False"
    type: Succeeded
```

The expected behavior is to maintain all of the condition that occurred during the run of the vm-import process.

Noticed on https://github.com/kubevirt/vm-import-operator/pull/310#discussion_r449201548
When this issue is fixed, tests can be changed to expect the 'Valid' condition with the desired reason for the validation failure.
