### ISSUE TITLE
Memory and Disk sizes in DV should be specified at least in Ki

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#72]
- or convert to the highest compatible unit

**Comment by pkliczewski** [comment]
@suomiy please add some examples

**Comment by atiratree** [comment]
for example in vm spec
```
        resources:
          limits:
            memory: '536870912'
          requests:
            memory: '536870912'
```

This could read `512 Mi` instead

or the datavolume spec

```
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '46137344'
    storageClassName: local
```

it could read `44Mi`
