### ISSUE TITLE
questions about Conditions' status 

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#75]
Shouldn't the condition status be `'False'` once that condition ceases to be relevant?

It seems like all the actions (Validating, Processing) are still happening with the following example even though the import has already finished :

```yaml
   - lastHeartbeatTime: "2020-04-09T15:28:26Z"
      lastTransitionTime: "2020-04-09T15:28:26Z"
      message: Validating completed successfully
      reason: ValidationCompleted
      status: "True"
      type: Validating
    - lastHeartbeatTime: "2020-04-09T15:28:26Z"
      lastTransitionTime: "2020-04-09T15:28:26Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
    - lastHeartbeatTime: "2020-04-09T15:28:27Z"
      lastTransitionTime: "2020-04-09T15:28:27Z"
      message: Copying virtual machine disks
      reason: CopyingDisks
      status: "True"
      type: Processing
    - lastHeartbeatTime: "2020-04-09T15:28:45Z"
      lastTransitionTime: "2020-04-09T15:28:45Z"
      message: Virtual machine disks import done
      reason: VirtualMachineReady
      status: "True"
      type: Succeeded
``` 

Or second option change the types, so they are not reffering to present tense like `Validating`?

Or how should a user read these?
