### ISSUE TITLE
Incorrect Suceeded and Processing conditions

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#84]
#### ! this comment is not relevant anymore - please see following posts

~every few second the condition changes from~

```
    - lastHeartbeatTime: "2020-04-14T12:10:09Z"
      lastTransitionTime: "2020-04-14T12:06:28Z"
      message: Virtual machine disks import done
      reason: VirtualMachineReady
      status: "True"
      type: Succeeded
```

~to~ 

```
    - lastHeartbeatTime: "2020-04-14T12:10:24Z"
      lastTransitionTime: "2020-04-14T12:06:28Z"
      message: 'Error while creating virtual machine: virtualmachines.kubevirt.io
        "cirrosvm" already exists'
      reason: VMCreationFailed
      status: "True"
      type: Succeeded
```

~and vice versa~

**Comment by machacekondra** [comment]
Even with latest image? I think this was solved by https://github.com/kubevirt/vm-import-operator/pull/70

**Comment by atiratree** [comment]
I tried with this image as it is the newest: `https://quay.io/repository/jdzon/vm-import-operator`.

 @jakub-dzon is  #70 present in that image?

Did not happen to me with `https://quay.io/repository/machacekondra/vm-import-operator`, but might be a reproducibility issue in case  #70 was present?

**Comment by jakub-dzon** [comment]
Hard to say right now:/ It is possible that #70 was not there.
I've just built the latest master: quay.io/jdzon/vm-import-operator:v0.0.2

**Comment by atiratree** [comment]
latest image (`quay.io/jdzon/vm-import-operator:v0.0.2`) behaviour:

- no DVs or PVCs were created and the VM entity was
- cycles between these two states

```yaml
    - lastHeartbeatTime: "2020-04-14T12:56:31Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: Validating completed successfully
      reason: ValidationCompleted
      status: "True"
      type: Validating
    - lastHeartbeatTime: "2020-04-14T12:56:31Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
    - lastHeartbeatTime: "2020-04-14T13:00:53Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: Copying virtual machine disks
      reason: CopyingDisks
      status: "True"
      type: Processing
    - lastHeartbeatTime: "2020-04-14T13:00:53Z"
      lastTransitionTime: "2020-04-14T12:56:34Z"
      message: 'Error while creating virtual machine: virtualmachines.kubevirt.io
        "cirrosvm" already exists'
      reason: VMCreationFailed
      status: "False"
      type: Succeeded
```

vs

```yaml
    - lastHeartbeatTime: "2020-04-14T12:56:31Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: Validating completed successfully
      reason: ValidationCompleted
      status: "True"
      type: Validating
    - lastHeartbeatTime: "2020-04-14T12:56:31Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
    - lastHeartbeatTime: "2020-04-14T13:01:12Z"
      lastTransitionTime: "2020-04-14T12:56:31Z"
      message: Creating virtual machine
      reason: CreatingTargetVM
      status: "True"
      type: Processing
    - lastHeartbeatTime: "2020-04-14T13:01:12Z"
      lastTransitionTime: "2020-04-14T12:56:34Z"
      message: 'Error while creating virtual machine: virtualmachines.kubevirt.io
        "cirrosvm" already exists'
      reason: VMCreationFailed
      status: "False"
      type: Succeeded
```

**Comment by machacekondra** [comment]
It doesn't happen to me, but I will investigate.

**Comment by atiratree** [comment]
thanks

used CR:

```yaml
apiVersion: v1
items:
- apiVersion: v2v.kubevirt.io/v1alpha1
  kind: VirtualMachineImport
  metadata:
    name: vm-import-cirrosvm-8bccf
    namespace: default
  spec:
    providerCredentialsSecret:
      name: admin-10-37-140-88-rhev-lab-en-lnxst
      namespace: default
    source:
      ovirt:
        mappings:
          diskMappings:
          - source:
              id: 64302e7f-3f08-4d32-9fe1-59b6c383acb5
            target:
              name: local
          networkMappings: []
          storageMappings: []
        vm:
          id: c1a784d6-4747-4c26-8b47-d3d6766436e1
    startVM: false
    targetVmName: cirrosvm

```
