### ISSUE TITLE
VM memory units

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#99]
is this behaving properly, why is it different?

```yaml
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 1023Mi
```
